# -*- coding: utf-8 -*-
"""GAN_XRay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUR6q4C9wYQPcLvp5VJmaSMpY8aD9Jiw
"""

import os
import json

kaggle_dict = {
    "username": "ritwikupadhyay17",
    "key": "ea710bb4558ed9719275e138f7454309"
}

os.makedirs("/root/.kaggle", exist_ok=True)

with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump(kaggle_dict, f)

os.chmod("/root/.kaggle/kaggle.json", 600)

!pip install kaggle

!pip install kagglehub

import kagglehub
path = kagglehub.dataset_download("andrewmvd/ct-low-dose-reconstruction")

import os

print(path)
print(os.listdir(path))

folder = os.path.join(path, "Preprocessed_256x256")
print(os.listdir(folder))

folder = os.path.join(path, "Preprocessed_256x256", "256")
print(os.listdir(folder))

from PIL import Image
from torch.utils.data import Dataset
import torchvision.transforms as transforms
import os

class CTDataset(Dataset):
    def __init__(self, root):
        self.low_root = os.path.join(root, "Quarter Dose", "3mm", "Soft Kernel (B30)")
        self.high_root = os.path.join(root, "Full Dose", "3mm", "Soft Kernel (B30)")

        self.pairs = []

        for patient in os.listdir(self.low_root):
            low_patient = os.path.join(self.low_root, patient)
            high_patient = os.path.join(self.high_root, patient)

            if os.path.isdir(low_patient) and os.path.isdir(high_patient):

                low_imgs = sorted(os.listdir(low_patient))
                high_imgs = sorted(os.listdir(high_patient))

                # pair by index
                for l, h in zip(low_imgs, high_imgs):
                    self.pairs.append((
                        os.path.join(low_patient, l),
                        os.path.join(high_patient, h)
                    ))

        self.transform = transforms.Compose([
            transforms.Grayscale(),
            transforms.ToTensor(),
            transforms.Normalize((0.5,), (0.5,))
        ])

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        low_path, high_path = self.pairs[idx]

        low = Image.open(low_path)
        high = Image.open(high_path)

        low = self.transform(low)
        high = self.transform(high)

        return low, high

dataset = CTDataset(folder)

print("Total samples:", len(dataset))

from torch.utils.data import DataLoader

loader = DataLoader(dataset, batch_size=8, shuffle=True)

for low, high in loader:
    print(low.shape)
    break

import torch.nn as nn

class Generator(nn.Module):
    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1),   # downsample
            nn.ReLU(),

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(),

            nn.ConvTranspose2d(128, 64, 4, 2, 1),  # upsample
            nn.BatchNorm2d(64),
            nn.ReLU(),

            nn.ConvTranspose2d(64, 1, 4, 2, 1),
            nn.Tanh()   # output [-1,1]
        )

    def forward(self, x):
        return self.model(x)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1),
            nn.LeakyReLU(0.2),

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),

            nn.Flatten(),
            nn.Linear(128 * 64 * 64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

G = Generator().to(device)
D = Discriminator().to(device)

criterion = nn.BCELoss()   # real/fake loss
l1_loss = nn.L1Loss()      # image similarity

opt_D = torch.optim.Adam(D.parameters(), lr=0.00005)
opt_G = torch.optim.Adam(G.parameters(), lr=0.0002)

epochs = 20

for epoch in range(epochs):
    for low, high in loader:

        low = low.to(device)
        high = high.to(device)

        # ------------------
        # Train Discriminator
        # ------------------
        fake = G(low)

        real_label = torch.full((low.size(0), 1), 0.9, device=device)
        fake_label = torch.full((low.size(0), 1), 0.1, device=device)

        # real images
        loss_real = criterion(D(high), real_label)

        # fake images
        loss_fake = criterion(D(fake.detach()), fake_label)

        loss_D = loss_real + loss_fake

        opt_D.zero_grad()
        loss_D.backward()
        opt_D.step()

        # ------------------
        # Train Generator
        # ------------------

        for _ in range(2):
            fake = G(low)  # regenerate

            loss_G_adv = criterion(D(fake), real_label)
            loss_G_l1 = l1_loss(fake, high)


            loss_G = loss_G_adv + 50 * loss_G_l1

            opt_G.zero_grad()
            loss_G.backward()
            opt_G.step()

    # ------------------
    # PRINT PROGRESS
    # ------------------
    print(f"Epoch {epoch+1}/{epochs} | D Loss: {loss_D.item():.4f} | G Loss: {loss_G.item():.4f}")

    # ------------------
    # SHOW OUTPUT EVERY 5 EPOCHS
    # ------------------
    if (epoch + 1) % 5 == 0:
        low_sample, high_sample = next(iter(loader))
        low_sample = low_sample.to(device)

        fake_sample = G(low_sample).detach().cpu()

        import matplotlib.pyplot as plt
        plt.figure(figsize=(10,3))

        plt.subplot(1,3,1)
        plt.imshow(low_sample[0][0].cpu(), cmap='gray')
        plt.title("Low")

        plt.subplot(1,3,2)
        plt.imshow(fake_sample[0][0], cmap='gray')
        plt.title("Generated")

        plt.subplot(1,3,3)
        plt.imshow(high_sample[0][0], cmap='gray')
        plt.title("Real")

        plt.show()

torch.save(G.state_dict(), "generator_final.pth")

torch.save(D.state_dict(), "discriminator_final.pth")

from google.colab import drive
drive.mount('/content/drive')

torch.save(G.state_dict(), "/content/drive/MyDrive/generator_final.pth")

from google.colab import files
files.download("generator_final.pth")

torch.save({
    'generator': G.state_dict(),
    'discriminator': D.state_dict()
}, "/content/drive/MyDrive/gan_model_full.pth")

import torch
import random
import matplotlib.pyplot as plt

# ------------------------
# LOAD MODEL
# ------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"

G = Generator().to(device)
G.load_state_dict(torch.load("generator_final.pth", map_location=device))
G.eval()

# ------------------------
# TEST MULTIPLE SAMPLES
# ------------------------
num_samples = 10

for i in range(num_samples):

    idx = random.randint(0, len(dataset) - 1)
    low, high = dataset[idx]

    low_input = low.unsqueeze(0).to(device)

    with torch.no_grad():
        fake = G(low_input).cpu()

    fake_img = fake[0][0]
    low_img = low[0]
    high_img = high[0]

    # ------------------------
    # MAIN COMPARISON
    # ------------------------
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(low_img, cmap='gray')
    plt.title("Low Dose")

    plt.subplot(1,3,2)
    plt.imshow(fake_img, cmap='gray')
    plt.title("Generated")

    plt.subplot(1,3,3)
    plt.imshow(high_img, cmap='gray')
    plt.title("High Dose")

    plt.suptitle(f"Sample {i+1} (Index {idx})")
    plt.show()

    # ------------------------
    # ZOOMED COMPARISON
    # ------------------------
    x1, x2 = 80, 160
    y1, y2 = 80, 160

    plt.figure(figsize=(10,3))

    plt.subplot(1,3,1)
    plt.imshow(low_img[x1:x2, y1:y2], cmap='gray')
    plt.title("Low Zoom")

    plt.subplot(1,3,2)
    plt.imshow(fake_img[x1:x2, y1:y2], cmap='gray')
    plt.title("Generated Zoom")

    plt.subplot(1,3,3)
    plt.imshow(high_img[x1:x2, y1:y2], cmap='gray')
    plt.title("High Zoom")

    plt.show()

    # ------------------------
    # DIFFERENCE MAP
    # ------------------------
    diff = abs(high_img - fake_img)

    plt.figure(figsize=(4,4))
    plt.imshow(diff, cmap='hot')
    plt.title("Difference Map")
    plt.colorbar()
    plt.show()

    # ------------------------
    # VALUE RANGE DEBUG
    # ------------------------
    print("Low range:", low_img.min().item(), "to", low_img.max().item())
    print("Generated range:", fake_img.min().item(), "to", fake_img.max().item())
    print("High range:", high_img.min().item(), "to", high_img.max().item())

    print("-" * 50)